### ISSUE TITLE
Create basic Roadmap

### ISSUE THREAD

**Issue by on3iro** [on3iro/BGAchievements#11]
# Road to 1.0.0

## Prerequisite phase

* [ ] Determine initial feature set
* [ ] Create Mockups
* [ ] Create basic designs
* [ ] Create static prototype
* [ ] Create data model
* [ ] Create project baseline / dev / deployment workflow

## Frontend phase

* [ ] Implement initial feature set
* [ ] Add CSS for different screen sizes

## Backend phase + Alpha phase

* [ ] Implement backend logic
* [ ] Host backend (DigitalOcean, Linode, Vultr)
* [ ] Host frontend
* [ ] Maybe add custom domain
* [ ] Tests and bugfixes

## Beta phase
* [ ] Invite some testers
* [ ] Bugfix
* [ ] Discuss user feedback, make occasional changes
* [ ] Monitor performance

## Post go live
* [ ] Additional features
* [ ] Maintenance

@Thoryk @jannydiamond What do you think?
I will probably add an extra ROADMAP.md file to the project and link to it from the README.
Whenever we settle on new features I will add them to the ROADMAP, so that we have a visual indicator of feature prioritization. Most phases will probably also resemble milestones. Therefore I will add links to the respective milestone to the ROADMAP whenever possible.

**Comment by on3iro** [comment]
I'll close this for now. We have a basic roadmap inside our README, now.
We can still refer to this issue, but we need to do more planning anyway and will eventually come up with something more representative of  our actual roadmap. ... we might then re-open and  update this..
